<?php
/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2019-2022 PensoPay <https://pensopay.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package default_default
 */
/** @var Mage_Core_Block_Template $this */
?>
<div style="display:none">
    <a id="paymentLink" target="_blank" href="<?= $this->getPaymentLink(); ?>"></a>
</div>
<?php if ($this->getPaymentLinkAutovisit()): ?>
    <script type="text/javascript">
        $('paymentLink').click();
    </script>
<?php endif; ?>