<?php
/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2019-2022 PensoPay <https://pensopay.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
/** @var PensoPay_Payment_Block_Form $this */
?>
<?php $_code = $this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
            <?php echo nl2br($this->getConfigData('instructions')); ?>
            <?php if ((int)$this->getConfigData('transactionfee') == 1): ?>
                <?php if ($this->getConfigData('transactionfee')) : ?>
                    <br>
                    <br>
                    <b><?php echo Mage::helper('pensopay')->__("Tranaktionsgebyr"); ?></b>
                    <br>
                    <?php echo Mage::helper('pensopay')->__("Der vil blive opkrævet et transaktionsgebyr ved brug af denne betalingsmetode. Gebyr størrelsen afhænger af kortvalg og vil blive tilføjet ved betaling."); ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </li>
</ul>