<?php
/**
 * SPDX-FileCopyrightText: 2006-2020 Magento, Inc. <http://www.magento.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
?>
<?php
/** @var Mage_Checkout_Block_Agreements $this */
?>

<?php if (!$this->getAgreements()) return; ?>
<ol class="mobilepay-checkout-agreements">
<?php foreach ($this->getAgreements() as $_a): ?>
    <li>
        <div id="mobilepay-agreement-modal" class="agreement-content mfp-hide white-popup"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
            <?php if ($_a->getIsHtml()):?>
                <?php echo $_a->getContent() ?>
            <?php else:?>
                <?= nl2br((string) $this->escapeHtmlAsObject($_a->getContent())) ?>
            <?php endif; ?>

            <div class="action">
                <button class="button mobilepay-checkout-agreements-close" type="button" title="<?php echo $this->__('Close'); ?>"><?php echo $this->__('Close'); ?></button>
            </div>
        </div>
        <p class="agree">
            <input type="checkbox" id="mobilepay-agreement-<?= $_a->getId()?>" name="agreement[<?= $_a->getId()?>]" value="1" title="<?= $this->escapeHtmlAsObject($_a->getCheckboxText()) ?>" class="checkbox agreement required-entry" /><a href="#mobilepay-agreement-modal" class="mobilepay-agreement-modal" for="agreement-<?= $_a->getId()?>"><?= $_a->getIsHtml() ? $_a->getCheckboxText() : $this->escapeHtmlAsObject($_a->getCheckboxText()) ?></a>
        </p>
    </li>
<?php endforeach ?>
</ol>

<script>
    (function($){
        $('.mobilepay-agreement-modal').magnificPopup({
            type: 'inline'
        });
        $(document).on('click', '.mobilepay-checkout-agreements-close, #mobilepay-agreement-modal .mfp-close', function (e) {
            $.magnificPopup.open({
                items: {
                    src: '#mobilepay-modal'
                },
                type: 'inline'
            });
        });
    })(jQuery);
</script>