<?php
/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2019-2022 PensoPay <https://pensopay.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
    $quote = Mage::getSingleton('checkout/session')->getQuote();
?>
<tr>
    <td colspan="2" class="a-right">
        <div class="viabill-pricetag" data-view="basket" data-price="<?= $quote->getGrandTotal(); ?>"></div>
    </td>
</tr>