<?php
/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2019-2022 PensoPay <https://pensopay.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
/** @var Mage_Core_Block_Template $this */
/** @var Mage_Catalog_Model_Product $_product */
$_product = $this->getProduct();
//specific currency only?
$_view = $this->getView();
?>
<div class="viabill-pricetag" data-view="<?= $_view ?>" data-price="<?= number_format($_product->getFinalPrice(), 2); ?>"></div>