<?php
/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-FileCopyrightText: 2019-2022 PensoPay <https://pensopay.com>
 * SPDX-License-Identifier: AFL-3.0
 * @package base_default
 */
/** @var PensoPay_Payment_Block_Mpo_Link $this */
?>
<?php if ($this->isMobilePayCheckoutEnabled()): ?>
    <a href="<?php echo $this->getCheckoutUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/pensopaypayment/mobilepay_checkout.png'); ?>" height="33" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Checkout with MobilePay')); ?>"></a>
<?php endif; ?>
